# ClawCat Configuration File
# This is a sample configuration for testing

# Application settings
app:
  debug: true
  log_level: "info"
  
# File paths
paths:
  data_dir: "~/.claude"
  cache_dir: "~/.cache/clawcat"

# UI settings  
ui:
  theme: "dark"
  refresh_interval: "1s"
  page_size: 20

# Cache settings
cache:
  max_memory: "200MB"
  eviction_policy: "lru"

# Export settings
export:
  default_format: "csv"
  include_metadata: true